# -*- coding: utf-8 -*-
"""PRIME NUMBERS?

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IRCEhunTp2lcsfLDdXrXC45KM4cAYdHM
"""

numbers = int(input("Please enter a positive integer:  "))
prime_numbers = []

for number in range(2, numbers + 1): 
  counter = 0
  for i in range(1, number + 1):
    if number % i == 0 :
      counter +=1

  if counter == 2 :  
    prime_numbers.append(number) 

print(prime_numbers)